version : '2.2'

networks:
  default:
    external:
      name: elfstore-network

services :
  edge1:
    image: elfstorenojson
    mem_limit: 1024m
    cpus: 1
    volumes:
      - ./Logs/edgeClientLogs/:/edgefs/logs/
      - ./Logs/edgeServerLogs/:/log.dir_IS_UNDEFINED/
    networks:
      default:
        ipv4_address: 174.10.10.0
    expose:
      - "7000"
    command: java -Xms40m -Xmx200m  -cp edgefs/cli/target/edgefilesystem-0.1-jar-with-dependencies.jar com.dreamlab.edgefs.edge.server.EdgeServer 1 174.10.10.0 7000 88 174.10.20.2 9090  /edgedatatemp  /edgefs/logs

  edge2:
    image: elfstorenojson
    mem_limit: 1024m
    cpus: 1
    volumes:
      - ./Logs/edgeClientLogs/:/edgefs/logs/
      - ./Logs/edgeServerLogs/:/log.dir_IS_UNDEFINED/
    networks:
      default:
        ipv4_address: 174.10.10.1
    expose:
      - "7001"
    command: java -Xms40m -Xmx200m  -cp edgefs/cli/target/edgefilesystem-0.1-jar-with-dependencies.jar com.dreamlab.edgefs.edge.server.EdgeServer 2 174.10.10.1 7001 93 174.10.20.2 9090  /edgedatatemp  /edgefs/logs

  edge3:
    image: elfstorenojson
    mem_limit: 1024m
    cpus: 1
    volumes:
      - ./Logs/edgeClientLogs/:/edgefs/logs/
      - ./Logs/edgeServerLogs/:/log.dir_IS_UNDEFINED/
    networks:
      default:
        ipv4_address: 174.10.10.2
    expose:
      - "7002"
    command: java -Xms40m -Xmx200m  -cp edgefs/cli/target/edgefilesystem-0.1-jar-with-dependencies.jar com.dreamlab.edgefs.edge.server.EdgeServer 3 174.10.10.2 7002 91 174.10.20.2 9090  /edgedatatemp  /edgefs/logs

  edge4:
    image: elfstorenojson
    mem_limit: 1024m
    cpus: 1
    volumes:
      - ./Logs/edgeClientLogs/:/edgefs/logs/
      - ./Logs/edgeServerLogs/:/log.dir_IS_UNDEFINED/
    networks:
      default:
        ipv4_address: 174.10.10.3
    expose:
      - "7003"
    command: java -Xms40m -Xmx200m  -cp edgefs/cli/target/edgefilesystem-0.1-jar-with-dependencies.jar com.dreamlab.edgefs.edge.server.EdgeServer 4 174.10.10.3 7003 90 174.10.20.2 9090  /edgedatatemp /edgefs/logs

  edge5:
    image: elfstorenojson
    mem_limit: 1024m
    cpus: 1
    volumes:
      - ./Logs/edgeClientLogs/:/edgefs/logs/
      - ./Logs/edgeServerLogs/:/log.dir_IS_UNDEFINED/
    networks:
      default:
        ipv4_address: 174.10.10.4
    expose:
      - "7004"
    command: java -Xms40m -Xmx200m  -cp edgefs/cli/target/edgefilesystem-0.1-jar-with-dependencies.jar com.dreamlab.edgefs.edge.server.EdgeServer 5 174.10.10.4 7004 88 174.10.20.3 9091  /edgedatatemp /edgefs/logs

  edge6:
    image: elfstorenojson
    mem_limit: 1024m
    cpus: 1
    volumes:
      - ./Logs/edgeClientLogs/:/edgefs/logs/
      - ./Logs/edgeServerLogs/:/log.dir_IS_UNDEFINED/
    networks:
      default:
        ipv4_address: 174.10.10.5
    expose:
      - "7005"
    command: java -Xms40m -Xmx200m  -cp edgefs/cli/target/edgefilesystem-0.1-jar-with-dependencies.jar com.dreamlab.edgefs.edge.server.EdgeServer 6 174.10.10.5 7005 89 174.10.20.3 9091  /edgedatatemp /edgefs/logs

  edge7:
    image: elfstorenojson
    mem_limit: 1024m
    cpus: 1
    volumes:
      - ./Logs/edgeClientLogs/:/edgefs/logs/
      - ./Logs/edgeServerLogs/:/log.dir_IS_UNDEFINED/
    networks:
      default:
        ipv4_address: 174.10.10.6
    expose:
      - "7006"
    command: java -Xms40m -Xmx200m  -cp edgefs/cli/target/edgefilesystem-0.1-jar-with-dependencies.jar com.dreamlab.edgefs.edge.server.EdgeServer 7 174.10.10.6 7006 95 174.10.20.3 9091  /edgedatatemp /edgefs/logs

  edge8:
    image: elfstorenojson
    mem_limit: 1024m
    cpus: 1
    volumes:
      - ./Logs/edgeClientLogs/:/edgefs/logs/
      - ./Logs/edgeServerLogs/:/log.dir_IS_UNDEFINED/
    networks:
      default:
        ipv4_address: 174.10.10.7
    expose:
      - "7007"
    command: java -Xms40m -Xmx200m  -cp edgefs/cli/target/edgefilesystem-0.1-jar-with-dependencies.jar com.dreamlab.edgefs.edge.server.EdgeServer 8 174.10.10.7 7007 86 174.10.20.3 9091  /edgedatatemp /edgefs/logs
