version: '2.2'

networks:
  default:
    external:
      name: elfstore-network

services:
  edge9:
    container_name: edge9
    image: elfstorenojson
    mem_limit: 4096m
    cpus: 1
    volumes:
      - ./Logs/edgeClientLogs/:/edgefs/logs/
      - ./Logs/edgeServerLogs/:/log.dir_IS_UNDEFINED/
    networks:
      default:
       ipv4_address: 172.10.10.8
    expose:
      - "7008"
    command: bash -c "source tc_rule.sh && java -Xms40m -Xmx200m -cp edgefs/cli/target/edgefilesystem-0.1-jar-with-dependencies.jar com.dreamlab.edgefs.edge.server.EdgeServer 9 172.10.10.8 7008 88 172.10.20.2 9002  /edgefs/data  /edgefs/logs"

  edge10:
    container_name: edge10
    image: elfstorenojson
    mem_limit: 4096m
    cpus: 1
    volumes:
      - ./Logs/edgeClientLogs/:/edgefs/logs/
      - ./Logs/edgeServerLogs/:/log.dir_IS_UNDEFINED/
    networks:
      default:
       ipv4_address: 172.10.10.9
    expose:
      - "7009"
    command: bash -c "source tc_rule.sh && java -Xms40m -Xmx200m -cp edgefs/cli/target/edgefilesystem-0.1-jar-with-dependencies.jar com.dreamlab.edgefs.edge.server.EdgeServer 10 172.10.10.9 7009 88 172.10.20.2 9002  /edgefs/data  /edgefs/logs"

  edge11:
    container_name: edge11
    image: elfstorenojson
    mem_limit: 4096m
    cpus: 1
    volumes:
      - ./Logs/edgeClientLogs/:/edgefs/logs/
      - ./Logs/edgeServerLogs/:/log.dir_IS_UNDEFINED/
    networks:
      default:
       ipv4_address: 172.10.10.10
    expose:
      - "7010"
    command: bash -c "source tc_rule.sh && java -Xms40m -Xmx200m -cp edgefs/cli/target/edgefilesystem-0.1-jar-with-dependencies.jar com.dreamlab.edgefs.edge.server.EdgeServer 11 172.10.10.10 7010 88 172.10.20.2 9002  /edgefs/data  /edgefs/logs"

  edge12:
    container_name: edge12
    image: elfstorenojson
    mem_limit: 4096m
    cpus: 1
    volumes:
      - ./Logs/edgeClientLogs/:/edgefs/logs/
      - ./Logs/edgeServerLogs/:/log.dir_IS_UNDEFINED/
    networks:
      default:
       ipv4_address: 172.10.10.11
    expose:
      - "7011"
    command: bash -c "source tc_rule.sh && java -Xms40m -Xmx200m -cp edgefs/cli/target/edgefilesystem-0.1-jar-with-dependencies.jar com.dreamlab.edgefs.edge.server.EdgeServer 12 172.10.10.11 7011 88 172.10.20.2 9002  /edgefs/data  /edgefs/logs"

  edge13:
    container_name: edge13
    image: elfstorenojson
    mem_limit: 4096m
    cpus: 1
    volumes:
      - ./Logs/edgeClientLogs/:/edgefs/logs/
      - ./Logs/edgeServerLogs/:/log.dir_IS_UNDEFINED/
    networks:
      default:
       ipv4_address: 172.10.10.12
    expose:
      - "7012"
    command: bash -c "source tc_rule.sh && java -Xms40m -Xmx200m -cp edgefs/cli/target/edgefilesystem-0.1-jar-with-dependencies.jar com.dreamlab.edgefs.edge.server.EdgeServer 13 172.10.10.12 7012 88 172.10.20.3 9003  /edgefs/data  /edgefs/logs"

  edge14:
    container_name: edge14
    image: elfstorenojson
    mem_limit: 4096m
    cpus: 1
    volumes:
      - ./Logs/edgeClientLogs/:/edgefs/logs/
      - ./Logs/edgeServerLogs/:/log.dir_IS_UNDEFINED/
    networks:
      default:
       ipv4_address: 172.10.10.13
    expose:
      - "7013"
    command: bash -c "source tc_rule.sh && java -Xms40m -Xmx200m -cp edgefs/cli/target/edgefilesystem-0.1-jar-with-dependencies.jar com.dreamlab.edgefs.edge.server.EdgeServer 14 172.10.10.13 7013 88 172.10.20.3 9003  /edgefs/data  /edgefs/logs"

  edge15:
    container_name: edge15
    image: elfstorenojson
    mem_limit: 4096m
    cpus: 1
    volumes:
      - ./Logs/edgeClientLogs/:/edgefs/logs/
      - ./Logs/edgeServerLogs/:/log.dir_IS_UNDEFINED/
    networks:
      default:
       ipv4_address: 172.10.10.14
    expose:
      - "7014"
    command: bash -c "source tc_rule.sh && java -Xms40m -Xmx200m -cp edgefs/cli/target/edgefilesystem-0.1-jar-with-dependencies.jar com.dreamlab.edgefs.edge.server.EdgeServer 15 172.10.10.14 7014 88 172.10.20.3 9003  /edgefs/data  /edgefs/logs"

  edge16:
    container_name: edge16
    image: elfstorenojson
    mem_limit: 4096m
    cpus: 1
    volumes:
      - ./Logs/edgeClientLogs/:/edgefs/logs/
      - ./Logs/edgeServerLogs/:/log.dir_IS_UNDEFINED/
    networks:
      default:
       ipv4_address: 172.10.10.15
    expose:
      - "7015"
    command: bash -c "source tc_rule.sh && java -Xms40m -Xmx200m -cp edgefs/cli/target/edgefilesystem-0.1-jar-with-dependencies.jar com.dreamlab.edgefs.edge.server.EdgeServer 16 172.10.10.15 7015 88 172.10.20.3 9003  /edgefs/data  /edgefs/logs"
