version: '2.2'

networks:
  default:
    external:
      name: elfstore-network

services:
  edge1:
    container_name: edge1
    image: elfstorenojson
    mem_limit: 4096m
    cpus: 1
    volumes:
      - ./Logs/edgeClientLogs/:/edgefs/logs/
      - ./Logs/edgeServerLogs/:/log.dir_IS_UNDEFINED/
    networks:
      default:
       ipv4_address: 172.10.10.0
    expose:
      - "7000"
    command: bash -c "source tc_rule.sh && java -Xms40m -Xmx200m -cp edgefs/cli/target/edgefilesystem-0.1-jar-with-dependencies.jar com.dreamlab.edgefs.edge.server.EdgeServer 1 172.10.10.0 7000 88 172.10.20.0 9000  /edgefs/data  /edgefs/logs"

  edge2:
    container_name: edge2
    image: elfstorenojson
    mem_limit: 4096m
    cpus: 1
    volumes:
      - ./Logs/edgeClientLogs/:/edgefs/logs/
      - ./Logs/edgeServerLogs/:/log.dir_IS_UNDEFINED/
    networks:
      default:
       ipv4_address: 172.10.10.1
    expose:
      - "7001"
    command: bash -c "source tc_rule.sh && java -Xms40m -Xmx200m -cp edgefs/cli/target/edgefilesystem-0.1-jar-with-dependencies.jar com.dreamlab.edgefs.edge.server.EdgeServer 2 172.10.10.1 7001 88 172.10.20.0 9000  /edgefs/data  /edgefs/logs"

  edge3:
    container_name: edge3
    image: elfstorenojson
    mem_limit: 4096m
    cpus: 1
    volumes:
      - ./Logs/edgeClientLogs/:/edgefs/logs/
      - ./Logs/edgeServerLogs/:/log.dir_IS_UNDEFINED/
    networks:
      default:
       ipv4_address: 172.10.10.2
    expose:
      - "7002"
    command: bash -c "source tc_rule.sh && java -Xms40m -Xmx200m -cp edgefs/cli/target/edgefilesystem-0.1-jar-with-dependencies.jar com.dreamlab.edgefs.edge.server.EdgeServer 3 172.10.10.2 7002 88 172.10.20.0 9000  /edgefs/data  /edgefs/logs"

  edge4:
    container_name: edge4
    image: elfstorenojson
    mem_limit: 4096m
    cpus: 1
    volumes:
      - ./Logs/edgeClientLogs/:/edgefs/logs/
      - ./Logs/edgeServerLogs/:/log.dir_IS_UNDEFINED/
    networks:
      default:
       ipv4_address: 172.10.10.3
    expose:
      - "7003"
    command: bash -c "source tc_rule.sh && java -Xms40m -Xmx200m -cp edgefs/cli/target/edgefilesystem-0.1-jar-with-dependencies.jar com.dreamlab.edgefs.edge.server.EdgeServer 4 172.10.10.3 7003 88 172.10.20.0 9000  /edgefs/data  /edgefs/logs"

  edge5:
    container_name: edge5
    image: elfstorenojson
    mem_limit: 4096m
    cpus: 1
    volumes:
      - ./Logs/edgeClientLogs/:/edgefs/logs/
      - ./Logs/edgeServerLogs/:/log.dir_IS_UNDEFINED/
    networks:
      default:
       ipv4_address: 172.10.10.4
    expose:
      - "7004"
    command: bash -c "source tc_rule.sh && java -Xms40m -Xmx200m -cp edgefs/cli/target/edgefilesystem-0.1-jar-with-dependencies.jar com.dreamlab.edgefs.edge.server.EdgeServer 5 172.10.10.4 7004 88 172.10.20.1 9001  /edgefs/data  /edgefs/logs"

  edge6:
    container_name: edge6
    image: elfstorenojson
    mem_limit: 4096m
    cpus: 1
    volumes:
      - ./Logs/edgeClientLogs/:/edgefs/logs/
      - ./Logs/edgeServerLogs/:/log.dir_IS_UNDEFINED/
    networks:
      default:
       ipv4_address: 172.10.10.5
    expose:
      - "7005"
    command: bash -c "source tc_rule.sh && java -Xms40m -Xmx200m -cp edgefs/cli/target/edgefilesystem-0.1-jar-with-dependencies.jar com.dreamlab.edgefs.edge.server.EdgeServer 6 172.10.10.5 7005 88 172.10.20.1 9001  /edgefs/data  /edgefs/logs"

  edge7:
    container_name: edge7
    image: elfstorenojson
    mem_limit: 4096m
    cpus: 1
    volumes:
      - ./Logs/edgeClientLogs/:/edgefs/logs/
      - ./Logs/edgeServerLogs/:/log.dir_IS_UNDEFINED/
    networks:
      default:
       ipv4_address: 172.10.10.6
    expose:
      - "7006"
    command: bash -c "source tc_rule.sh && java -Xms40m -Xmx200m -cp edgefs/cli/target/edgefilesystem-0.1-jar-with-dependencies.jar com.dreamlab.edgefs.edge.server.EdgeServer 7 172.10.10.6 7006 88 172.10.20.1 9001  /edgefs/data  /edgefs/logs"

  edge8:
    container_name: edge8
    image: elfstorenojson
    mem_limit: 4096m
    cpus: 1
    volumes:
      - ./Logs/edgeClientLogs/:/edgefs/logs/
      - ./Logs/edgeServerLogs/:/log.dir_IS_UNDEFINED/
    networks:
      default:
       ipv4_address: 172.10.10.7
    expose:
      - "7007"
    command: bash -c "source tc_rule.sh && java -Xms40m -Xmx200m -cp edgefs/cli/target/edgefilesystem-0.1-jar-with-dependencies.jar com.dreamlab.edgefs.edge.server.EdgeServer 8 172.10.10.7 7007 88 172.10.20.1 9001  /edgefs/data  /edgefs/logs"
