version : '2.2'

networks:
  default:
    external:
      name: elfstore-network

services :
  fog3:
    image: elfstorenojson
    mem_limit: 4096m
    cpus: 2
    volumes:
      - ./Logs/serverLogs/:/log.dir_IS_UNDEFINED/
    networks:
      default:
        ipv4_address: 174.10.0.4
    expose:
      - "9092"
    command: java -Xms80m -Xmx800m -cp edgefs/cli/target/edgefilesystem-0.1-jar-with-dependencies.jar com.dreamlab.edgefs.controlplane.FogServer 174.10.0.4 9092 2 3 0.25 0

  fog4:
    image: elfstorenojson
    mem_limit: 4096m
    cpus: 2
    volumes:
      - ./Logs/serverLogs/:/log.dir_IS_UNDEFINED/
    networks:
      default:
        ipv4_address: 174.10.0.5
    expose:
      - "9093"
    command: java -Xms80m -Xmx800m -cp edgefs/cli/target/edgefilesystem-0.1-jar-with-dependencies.jar com.dreamlab.edgefs.controlplane.FogServer 174.10.0.5 9093 2 4 0.25 0
